### PR TITLE
Init Project

### PR DESCRIPTION
**Pull request by VanHieu7119**
Task: Init Project
Link Redmine: https://edu-redmine.framgia.vn/issues/2689

### CODE REVIEW

**Comment by VanHieu7119** [comment]
ready

**Comment by VanHieu7119** [comment]
ready

**Comment by VanHieu7119** [comment]
ready

**Comment by VanHieu7119** [comment]
ready

**Review by tuanlvt-1117 — APPROVED** [review]

**Comment by tuanlvt-1117** [comment]
merged

**Pull request merged**
